version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-euquero
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: euquero
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050

    ports:
      - "5050:5050"

volumes:
  data: